### PR TITLE
palindrome number

### PR DESCRIPTION
**Pull request by manyadua16**
c-based program for a palindromic number

### CODE REVIEW

**Comment by manyadua16** [comment]
Hey! I can see that you have accepted my pr and merged it but it isn't reflecting in my hacktober profile!

**Comment by Anuragcoderealy** [comment]
sometimes it takes it little time, wait for a few hours.

**Comment by manyadua16** [comment]
It isn't reflected till now, also can I make another pr in the same repository will it do?

**Comment by Anuragcoderealy** [comment]
ok sure

**Pull request merged**
